### ISSUE TITLE
PermissionsViewer: add option to collapse Permissions section

### ISSUE THREAD

**Issue by ddlr** [rauenzi/BetterDiscordAddons#40]
Hi! Thanks for making the PermissionsViewer plugin -- it's my second day using it, and already it's proven itself to be invaluable whenever I use Discord.

Sometimes I encounter users with a crazy amount of roles, and this in conjunction with the Permissions list causes the profile popup to no longer fit entirely in my small laptop screen:

![Screenshot of issue](https://user-images.githubusercontent.com/2908767/36060262-e2486130-0eaa-11e8-9cc7-3a9c8267d6e7.png)

While the dealing with the roles is of course beyond the scope of the plugin, I think an arrow button to optionally collapse the Permissions section would be immensely helpful in mitigating this issue.

**Comment by rauenzi** [comment]
You'd be better off limiting height with CSS

```css
.rolesList-2RhjNd {
	display: flex;
	flex-wrap: wrap;
	margin-top: 2px;
	max-height: 100px;
	overflow-y: auto;
}

.rolesList-2RhjNd::-webkit-scrollbar-thumb,
.rolesList-2RhjNd::-webkit-scrollbar-track {
	background-clip: padding-box;
	border-radius: 7.5px;
	border-style: solid;
	border-width: 3px;
	visibility: hidden;
}

.rolesList-2RhjNd:hover::-webkit-scrollbar-thumb,
.rolesList-2RhjNd:hover::-webkit-scrollbar-track {
	visibility: visible;
}

.rolesList-2RhjNd::-webkit-scrollbar-track {
	border-width: initial;
	background-color: transparent;
	border: 2px solid transparent;
}

.rolesList-2RhjNd::-webkit-scrollbar-thumb {
	border: 2px solid transparent;
	border-radius: 4px;
	cursor: move;
	background-color: rgba(32,34,37,.6);
}

.rolesList-2RhjNd::-webkit-scrollbar {
	height: 8px;
	width: 8px;
}

.member-perms {
    max-height: 100px;
}
```
