### ISSUE TITLE
[Bug] PermissionsViewer broken Permissions tab

### ISSUE THREAD

**Issue by someone19204** [rauenzi/BetterDiscordAddons#628]
**Which plugin/theme is this about?**

PermissionsViewer

**Describe the Bug**

Weird permissions

**To Reproduce**

1. Enable PermissionsViewer and click on a user

**Expected Behavior**

Normal permission gui

**Screenshots**

![image](https://user-images.githubusercontent.com/88501829/179347194-25172376-7acc-4653-b0ed-daec90efdf2a.png)

**Discord Version**

Stable 137095 (fb67ae9)

**Additional Context**

**Comment by KewlSage** [comment]
```css
.member-perm {
    display: flex;
    font-size: 12px;
    font-weight: 500;
    background: var(--background-secondary-alt);
    border-radius: 4px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: 22px;
    margin: 0 4px 4px 0;
    padding: 4px;
}
```
